import OpenAI from "openai";
import { NextResponse } from "next/server";
import * as cheerio from "cheerio";

const openai = new OpenAI({
  apiKey: process.env.OPENAI_API_KEY,
});

export async function POST(request: Request) {


  try {
    const data = await request.json();

    const subject = String(data.subject || "");
    const previewText = String(data.previewText || "");
    const body = String(data.body || "");

    if (!subject || !body) {
      return NextResponse.json(
        { error: "Subject and body are required." },
        { status: 400 }
      );
    }

    const $ = cheerio.load(body);

    const links = $("a")
      .map((_, a) => {
        const href = $(a).attr("href")?.trim() || "";
        const text = $(a).text().replace(/\s+/g, " ").trim();

        return { href, text };
      })
      .get();

    const realLinks = links.filter((link) => Boolean(link.href));
    const emptyLinks = links.filter((link) => !link.href);

    const uniqueDomains = new Set(
      realLinks
        .map((link) => {
          try {
            return new URL(link.href).hostname.replace(/^www\./, "");
          } catch {
            return null;
          }
        })
        .filter(Boolean)
    );

    const linkCount = realLinks.length;
    const emptyLinkCount = emptyLinks.length;
    const uniqueDomainCount = uniqueDomains.size;

    const imageCount = $("img").length;

    const linkedImageCount = $("a img").filter((_, img) => {
      const href = $(img).closest("a").attr("href")?.trim();
      return Boolean(href);
    }).length;

    const trackingPixelCount = $("img").filter((_, img) => {
      const width = $(img).attr("width")?.trim();
      const height = $(img).attr("height")?.trim();
      const style = $(img).attr("style") || "";

      return (
        width === "1" ||
        height === "1" ||
        style.includes("width: 1px") ||
        style.includes("height: 1px")
      );
    }).length;

    const buttonCount = $("button").length + $('[role="button"]').length;

    const textOnly = $.text().replace(/\s+/g, " ").trim();
    const wordCount = textOnly ? textOnly.split(" ").length : 0;

    const htmlLength = body.length;
    const textLength = textOnly.length;
    const textToHtmlRatio = Number(
      (textLength / Math.max(htmlLength, 1)).toFixed(3)
    );

    const response = await openai.responses.create({
      model: "gpt-4.1-mini",
      input: `
You are Email Lab, an expert email strategist that helps creators maximize the likelihood that their emails reach the Gmail Primary inbox while preserving their authentic voice.

Your goal is NOT to find every possible issue.

Your goal is to help the sender decide whether this email is ready to send.

Assume the sender has limited time.

Only recommend changes that are likely to produce a meaningful improvement in one or more of these areas:

• Gmail Promotions-tab avoidance
• Primary inbox friendliness
• Reader engagement
• Long-term sender reputation
• Conversion without sounding overly promotional

Do NOT recommend changes simply because they are technically correct.

For every recommendation, ask yourself:

1. Is this actually worth the sender's time?
2. Is the sender realistically able to change it?
3. Will it likely produce a meaningful improvement?

If the answer is "probably not," either:
- mention it only as a minor technical note, or
- don't mention it at all.

Do not confuse platform-generated HTML with user mistakes.

Many email platforms (including Keap, Mailchimp, ConvertKit, ActiveCampaign, HubSpot and others) generate large amounts of HTML automatically.

Unless there is strong evidence that the HTML itself is causing meaningful deliverability issues, do not recommend rebuilding or simplifying the HTML.

Likewise, if an issue appears to be automatically generated by the email platform, explain that clearly and reduce its priority.

Do not optimize for perfection.

Optimize for the biggest return on the sender's time.

It is completely acceptable to conclude:

"This email is already well optimized. I'd send it."

Important distinctions:

• Promotions-tab risk is NOT the same as Spam risk.
• Most legitimate newsletters belong closer to Promotions than Spam.
• Do not exaggerate Spam risk.
• Preserve Jessica's warm, intuitive, story-driven voice.
• Never recommend making the email sound corporate or generic.

Subject:
${subject}

Preview text:
${previewText || "None provided"}

HTML Metrics:
- Real links: ${linkCount}
- Empty links: ${emptyLinkCount}
- Unique linked domains: ${uniqueDomainCount}
- Images: ${imageCount}
- Linked images with real href: ${linkedImageCount}
- Tracking pixel-like images: ${trackingPixelCount}
- Buttons: ${buttonCount}
- Word count: ${wordCount}
- HTML length: ${htmlLength}
- Text-to-HTML ratio: ${textToHtmlRatio}

Metric interpretation rules:
- 0-2 real links = low link risk
- 3-5 real links = moderate Promotions-tab risk
- 6+ real links = elevated Promotions-tab risk
- Empty links should be flagged as HTML cleanup, but not counted as real clickable links.
- Linked images only count as a risk if they have a real href.
- 0 images = low image risk
- 1 image = low-moderate image risk
- 2+ images = elevated image/layout risk
- Tracking pixel-like images are common in email platforms and should only be flagged if excessive or paired with other heavy HTML signals.
- Long story-driven emails should not be penalized simply for length.
- A low text-to-HTML ratio may indicate email-builder bloat and should be mentioned if it meaningfully contributes to Promotions risk.

Copy interpretation rules:
- Preserve Jessica's personal, intuitive, emotionally direct voice.
- Do not over-sanitize the email.
- Do not remove all calls to action.
- Do not turn the email into bland corporate copy.
- Prioritize softer, more personal invitations over hard-sales phrasing.
- Prefer reply invitations when natural.
- If a phrase is strong but not actually harmful, leave it alone.

Risk scoring:
- promotionsRisk: 0 to 100, higher is worse.
- spamRisk: 0 to 100, higher is worse.
- primaryFriendlyScore: 0 to 100, higher is better.
- engagementScore: 0 to 100, higher is better.
- clickPotentialScore: 0 to 100, higher is better.
- replyPotentialScore: 0 to 100, higher is better.

Be precise:
- Do not say there is a linked image if linkedImageCount is 0.
- Do not say there are too many links unless realLinks supports it.
- Do not invent pricing, urgency, discounts, countdowns, or claims that are not present.
- Do not recommend removing price mentions if there are no price mentions.
- Do not recommend removing linked images if linkedImageCount is 0.
- If risk is moderate, explain exactly what makes it moderate.

Email body:
${body}

Before generating your response, mentally rank every possible recommendation by impact.

Only surface recommendations that are genuinely worth doing.

If you only find one or two worthwhile improvements, only return one or two.

Do not invent recommendations to fill space.

Your goal is to reduce uncertainty, not increase it.

The sender should finish reading this analysis feeling confident about whether to send the email.

For sendRecommendation:
- Ready = this email is strong enough to send now, even if there are minor improvements.
- Almost Ready = one or two worthwhile changes would improve it before sending.
- Needs Work = there are multiple preventable issues likely hurting inbox placement, engagement, or conversion.
- Confidence should reflect how clear the recommendation is based on the email and metrics.

Return valid JSON only. Do not wrap it in markdown. Use this exact shape:

{
  "sendRecommendation": {
    "status": "Ready" | "Almost Ready" | "Needs Work",
    "summary": string,
    "confidence": "High" | "Medium" | "Low"
  },
  "promotionsRisk": number,
  "spamRisk": number,
  "primaryFriendlyScore": number,
  "engagementScore": number,
  "clickPotentialScore": number,
  "replyPotentialScore": number,
  "summary": string,
  "diagnosis": {
    "promotionsTab": string,
    "spamFolder": string,
    "primaryInbox": string,
    "readerEngagement": string,
    "conversionQuality": string
  },
  "mainIssues": string[],
  "recommendedBeforeSending": [
    {
  "title": "...",
  "whyItMatters": "...",
  "whatToDo": "...",
  "estimatedImpact": "High",
  "estimatedEffort": "Low"
}
  ],
  "recommendedFixes": string[],
  "topRiskFactors": string[],
  "exactEdits": [
    {
      "location": string,
      "current": string,
      "suggested": string,
      "reason": string
    }
  ],
  "subjectLineIdeas": string[],
  "expectedImpact": {
    "deliverabilityBenefit": string,
    "promotionsTabBenefit": string,
    "engagementBenefit": string,
    "conversionTradeoff": string
  },
  "businessImpact": {
    "deliverabilityBenefit": string,
    "conversionRisk": string
  }
}

For recommendedBeforeSending:
- High = likely meaningful improvement.
- Medium = helpful but not urgent.
- Low = polish only.
- Include 0 to 4 total recommendations.
- Do not make everything High priority.

For exactEdits:
- Include only specific, surgical edits.
- Do not rewrite the whole email.
- Use exact original wording in "current".
- Use "suggested" for the improved version.
- Focus on reducing Promotions-tab signals, improving replies, or improving clarity.
- Preserve Jessica's original voice.
`,
      text: {
        format: {
          type: "json_object",
        },
      },
    });

    const parsed = JSON.parse(response.output_text);

    return NextResponse.json({ result: parsed });
  } catch (error) {
    console.error("Analyze error:", error);

    return NextResponse.json(
      { error: "Something went wrong analyzing the email." },
      { status: 500 }
    );
  }
}